{% set version = "1.28" %}

package:
  name: puremagic
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/puremagic/puremagic-{{ version }}.tar.gz
  sha256: 195893fc129657f611b86b959aab337207d6df7f25372209269ed9e303c1a8c0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install .  -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - python >=3.7

test:
  requires:
    - mypy
    - pip
  imports:
    - puremagic
  commands:
    - pip check
    - mypy -p puremagic

about:
  home: https://github.com/cdgriffith/puremagic
  license: MIT
  license_file: LICENSE
  summary: Pure python implementation of magic file detection
  description: |
    Pure python implementation of identifying files based off their magic numbers

extra:
  recipe-maintainers:
    - andreyz4k
    - bollwyvl
