{% set version = "1.25" %}

package:
  name: puremagic
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/puremagic/puremagic-{{ version }}.tar.gz
  sha256: 671c801158376c5f4a43c805edf7ef87d59337e243b03a8ce23d151a7a0e9c4d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install .  -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8

test:
  requires:
    - pip
  imports:
    - puremagic
  commands:
    - pip check

about:
  home: https://github.com/cdgriffith/puremagic
  license: MIT
  license_file: LICENSE
  summary: Pure python implementation of magic file detection
  description: |
    Pure python implementation of identifying files based off their magic numbers

extra:
  recipe-maintainers:
    - andreyz4k
    - bollwyvl
