{% set name = "puremagic" %}
{% set version = "1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cdgriffith/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 31e3ea095139c94de79b8d686637e0878dd7e59a602fee10dd2084c89396cec8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - puremagic

about:
  home: https://github.com/cdgriffith/puremagic
  license: MIT
  license_family: MIT
  license_file: LICENCE
  summary: Pure python implementation of magic file detection

  description: |
    puremagic is a pure python module that will identify a file based off it's magic numbers.
  doc_url: https://github.com/cdgriffith/puremagic
  dev_url: https://github.com/cdgriffith/puremagic

extra:
  recipe-maintainers:
    - andreyz4k
