{% set version = "1.29" %}

package:
  name: puremagic
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/puremagic/puremagic-{{ version }}.tar.gz
  sha256: 67c115db3f63d43b13433860917b11e2b767e5eaec696a491be2fb544f224f7a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install .  -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - mypy
    - pip
    - python {{ python_min }}
  imports:
    - puremagic
  commands:
    - pip check
    - mypy -p puremagic

about:
  home: https://github.com/cdgriffith/puremagic
  license: MIT
  license_file: LICENSE
  summary: Pure python implementation of magic file detection
  description: |
    Pure python implementation of identifying files based off their magic numbers

extra:
  recipe-maintainers:
    - andreyz4k
    - bollwyvl
