# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.0.0"
  python_check_max: "3.14"
  python_min: "3.12"
  # the tests are large, and have weird, sometimes intentionally misbehaved binaries
  run_test: false

package:
  name: puremagic
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/puremagic/puremagic-${{ version }}.tar.gz
  sha256: 224fe42b6b3467276a45914e12b5f40905dea0e87963adbe5289667e7c607851

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install .  -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
    - setuptools-scm >=6.2
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports: puremagic
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - if: run_tests
    then:
      files:
        source:
          - test/
      requirements:
        run:
          - pytest-cov
          - python ${{ python_min }}.*
      script:
        - coverage run --source=puremagic --branch -m pytest -vv --tb=long --color=yes
        - coverage report --show-missing --skip-covered --fail-under=76

about:
  license: MIT
  license_file: LICENSE
  summary: Pure python implementation of magic file detection
  homepage: https://pypi.org/project/puremagic
  repository: https://github.com/cdgriffith/puremagic
  description: |
    Pure python implementation of identifying files based off their magic numbers

extra:
  recipe-maintainers:
    - andreyz4k
    - bollwyvl
